name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} - Lesson ${{ matrix.lesson }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            test_script: test.sh
          - os: macos-latest
            shell: bash
            test_script: test.sh
          - os: windows-latest
            shell: cmd
            test_script: test.bat
        lesson: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    env:
      CONAN_HOME: ${{ github.workspace }}/.conan_home_${{ matrix.lesson }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Conan
      uses: conan-io/setup-conan@latest
      
    - name: Run test for lesson ${{ matrix.lesson }}
      shell: ${{ matrix.shell }}
      run: |
        cd lesson${{ matrix.lesson }}
        ${{ matrix.test_script }} 